apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomboid-server
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: zomboid
  template:
    metadata:
      labels:
        app: zomboid
    spec:
      containers:
        - name: zomboid
          image: etheth888/project-zomboid-arm64:main
          ports: 
            - containerPort: 16261
              hostPort: 16261
              protocol: UDP
            - contaienrPort: 16262
              hostPort: 16262
              protocol: UDP
            - containerPort: 27015
              hostPort: 27015
              protocol: TCP
          tty: true
          stdin: true

